### ISSUE TITLE
issue in class jdnss.java

### ISSUE THREAD

**Issue by apoojain** [drsjb80/JDNSS#11]
The import edu.msudenver.cs.jclo can not be resolved in eclipse coz there is no such package(edu.msudenver.cs.jclo) found.

**Comment by drsjb80** [comment]
Agreed. The dev branch has removed the dependency, but it's not working yet. If you clone the initial version, everything should build as that package is in place. Alternatively, one can get it via maven: http://repo1.maven.org/maven2/edu/msudenver/cs/JCLO/1.3.5/ and https://search.maven.org/#artifactdetails%7Cedu.msudenver.cs%7CJCLO%7C1.3.5%7Cjar

**Comment by apoojain** [comment]
Dear Sir,

Thank you so much, for solving the issue but there is another issue with
the logger class used in the project as traceEntry() is showing an error
that the function is not defined for logger class.I have used entry()
instead without any error so if the purpose is not get affected then can I
use entry() instead of traceEntry()?

I have attached a screenshot of the error, Please help me to get out of
this error.

**Comment by drsjb80** [comment]
A working version before any of the DNSSEC work can be created via:
```
git clone https://github.com/drsjb80/JDNSS.git
cd JDNSS/
git reset --hard 283628091c6025c918c4e967d18cde713af797ec
mvn package
java -jar target/jdnss-2.0.jar -p 5300 test.com
```
A version that should work and doesn't have either JCLO or JavaLN is c2ecb3f
Let me know if this helps or not. Thanks!

**Comment by apoojain** [comment]
mvn package command is not recognized as an internal or external command, operable program or batch file, the error is shown on cmd after giving mvn package command??

**Comment by drsjb80** [comment]
> On Jul 6, 2017, at 12:13 PM, apoojain <notifications@github.com> wrote:
> 
> mvn package command is not recognized as an internal or external command, operable program or batch file, the error is shown on cmd after giving mvn package command?
> 
	Sorry, that’s maven, a way of building packages. You’ll need to download it from https://maven.apache.org/

	Let me know if that helps. Thanks!

--
Steve Beaty | www.k336.org | steve.k336.org | @drsbj80

**Comment by apoojain** [comment]
After mvn package command, there were some errors, please check the errors in attached screenshot.
![img_20170707_152836](https://user-images.githubusercontent.com/29795104/27953654-3739a67c-632a-11e7-9571-4759c9423c77.jpg)

**Comment by drsjb80** [comment]
You’ll also need a Java compiler; you can download a Java Developer’s Kit from: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

	Let us know if this helps. Thanks!

--
Steve Beaty | www.k336.org | steve.k336.org | @drsbj80

**Comment by apoojain** [comment]
i already have jdk1.8.0_131 installed in my pc and eclipse as compiler. 
![img_20170707_190747](https://user-images.githubusercontent.com/29795104/27960145-ca5ea78c-6347-11e7-9d7d-20622c95d9d9.jpg)

**Comment by apoojain** [comment]
sir, jdk error has been solved, actually, I  was installing maven's path separately in the environment variable but I had to append it with the jdk path.
So sir now what to do next after all the commands?

**Comment by drsjb80** [comment]
I’m glad you solved the build problem; I was going to guess it was a path issue somewhere. First, download an example zone file from https://github.com/drsjb80/JDNSS/blob/master/test.com

Then, in one terminal, cmd.exe, or PowerShell window, run:

    java -jar target/jdnss-2.0.jar --port=5300

You should then be able to run the following queries (from a different window):

    nslookup -port=5300 test.com localhost
    nslookup -port=5300 www.test.com localhost
    nslookup -port=5300 -type=SOA test.com localhost
    nslookup -port=5300 -type=NS test.com localhost
    nslookup -port=5300 -type=MX test.com localhost
    nslookup -port=5300 -type=AAAA www.test.com localhost
    nslookup -port=5300 -type=TXT one.test.com localhost


--
Steve Beaty | www.k336.org | steve.k336.org | @drsbj80

**Comment by priyasrivastava12** [comment]
Hello sir ,
Goodmorning
 I and @apoojain working over this .
The above  written instruction of yours helped us throughout. We are able to run the command 
java -jar target/jdnss-2.0 --port=5300
As shown in screenshot.
It is not giving any error..but when we used another command window for nslookup commands then it is not recognising it..
As shown in screenshot

**Comment by apoojain** [comment]
Screenshots of the errors:-
![img-20170710-wa0005](https://user-images.githubusercontent.com/29795104/28015435-a23249ce-658d-11e7-8f51-acf33a187a4d.jpeg)
![img-20170710-wa0002](https://user-images.githubusercontent.com/29795104/28015436-a2640aae-658d-11e7-959d-4d499801452f.jpeg)

**Comment by priyasrivastava12** [comment]
Sir ....
There are some of the doubts regarding the project i will be really obiliged to you if u clear these doubts 
@doubts
1. The database which is used in this project.The db.java which is forming the connection with the database.do we need to write those commands given in test/db folder on the mysql command prompt to execute it.
...............
2.the commands are given in JDNDS/sec/test/system/DB .Do we need to run it as given in JDNSS/src/test/system/DB/Run.
.............
3. Do we need towrite the instructions written in src/test/system/DB/.choices
...............
4. Sir, do we have to execute all classes and folder statements specified in JDNSS/src/test/system .
Or they are just documentation .
.......
5. In test.com, the details given about the various claases like IN .where do we need to runbit or execute it.
................
6. In JDNSS/src/test the named folder has so many lig files that are being updated byvthr software itself.. Do they are used just for the purpose of having the log files details or anythings else ..
.............
7. What is test file all about?
In readme folder it was written it is a shell file..so how do we run it do we need to install ubuntu for that..because we are running project in windows.
.........
8. Cygwin ...we need to install it for running application on window ??? But for what purpose ..the codes given in linux require Cygwin to run it on windows ..Do the codes specified in this project are written in accordance with linux os..??
........
9. How do we run the code in windows and how do we connect with the various documentation given in various folder of the project ..Do we need to access each folder and write up the things written there in command prompt..
...
Thankyou Sir..

**Comment by apoojain** [comment]
Sir, thank you so much for your help all the above queries you sent, have been run successfully.
Here is another doubt that how we get addresses for more domain names or add other domain names and their addresses to the record.

**Comment by drsjb80** [comment]
In general, there is no need to use the database connection. It was added on behalf of a user who used a PowerDNS server and wanted to migrate this JDNSS. Almost everyone uses zone files. There is no need to pay attention to the .choices file, it is there for my debugging. The system tests might not work at the moment, though they should on a Linux system which is where I developed this originally. There is no general need to install cygwin or a Linux VM unless you are interested in more thorough testing and development. You can add as many zone files on the command line as you want. There are a number of example zone files in the test directory and there are many more available on the net. Let me know if you have any other questions. Thanks!
